# Конфигурация CLI клиента

title = "Configuration"

[server]
Address =  "localhost"
Host = "4010"

[user]
name = "Danil"
password = "827ccb0eea8a706c4c34a16891f84e7b"

[mask_number]
regular_expression = "^(?:\\+7|8|7)?(?:9\\d{9})$"
