# Конфигурация CLI клиента

title = "Configuration"

[server]
host =  "localhost"
port = 4010

[requests_path]
post = "/send_sms"

[user]
name = "Danil"
password = "827ccb0eea8a706c4c34a16891f84e7b"

[mask_number]
regular_expression = "^(?:\\+7|8|7)?(?:9\\d{9})$"
